baseurl = "http://www.simplyapproximate.com/"
languageCode = "en-gb"
title = "Simply Approximate"
theme = "hpstr-hugo-theme"
pluralizelisttitles = false
PygmentsCodeFences = true
Paginate = 5

[params]
	subtitle = "Thoughts on Physics, Data Science, Games, Books, Dance, and Culture"
	[params.author]
		name = "HPSTR"
		avatar = "/images/avatar.jpg"
		bio = "Thoughts on Physics, Data Science, Games, Books, Dance, and Culture"
		github = "dldx/hpstr-hugo-theme"
	[params.image]
	  feature = "/images/abstract-1.jpg"
	  credit = "dargadgetz"
	  creditlink = "http://www.dargadgetz.com/ios-7-abstract-wallpaper-pack-for-iphone-5-and-ipod-touch-retina/"
