baseurl = "http://www.simplyapproximate.com/"
languageCode = "en-us"
title = "Simply Approximate"
theme = "hpstr-hugo-theme"
pluralizelisttitles = false
PygmentsCodeFences = true
Paginate = 5
googleAnalytics = "UA-109450627-1"

[params]
	subtitle = "Thoughts on Physics, Data Science, Games, Books, Dance, and Culture"
	[params.author]
		name = "Brian Richards"
		avatar = "/images/avatar.jpg"
		bio = "Thoughts on Physics, Data Science, Games, Books, Dance, and Culture"
		github = "bgrich/simplyapproximate-blogdown-website"
		twitter = "@SimplyApprox"
#	[params.image]
#	  feature = "/images/abstract-1.jpg"
#	  credit = "dargadgetz"
#	  creditlink = "http://www.dargadgetz.com/ios-7-abstract-wallpaper-pack-for-iphone-5-and-ipod-touch-retina/"
