---
title: Games You Might Have Missed In 2017
author: Brian Richards
date: '2017-12-31'
slug: games-you-might-have-missed-in-2017
categories:
  - Video Games
tags:
  - Video Games
draft: no
share: false
comments: false
---

I am always interested in hearing about things that are incredibly influential 
to my friends. Considering how many books, video games, movies, TV shows, and 
other pieces of culture are created in a year it is easy to miss something. As 
such, here is a small list of video games that either came out in 2017 or that 
I played in 2017 that I think could be easily missed and are quite wonderful.

## 1. OneShot

If there is one game that you play in your new year, *OneShot* should be that 
game. *OneShot* is the story of a young person (cat?) who is lost in an 
unfamiliar world. To say anything more about it would likely spoil the game, 
but I can say that it is full of wonderful thoughtful moments and is 
incredibly touching.

## 2. Cosmic Star Heroine

Built in the vein of the old Phantasy Star games, *Cosmic Star Heroine* is a 
classic style JRPG from Zeboyd Games. I backed this on Kickstarter many years 
ago and really enjoyed the finished product. The story is great and the 
gameplay is super fun.

## 3. NieR: Automata and NieR

*NieR: Automata* is the only true AAA game release on this list. That being 
said, it is one of those games that if you weren't paying attention to it you 
might have missed. But more importantly, it's predecessor is a game that I 
missed originally and the release of *NieR: Automata* got me to play the 
original *NieR*. While you do not have to play *NieR* to enjoy *NieR: Automata*, 
I highly recommend finding an old copy if you have access to a PS3 or Xbox 360. 
Both games are a joy to play, have deeply moving stories, and feature some of 
the best soundtracks I have ever heard from a video game.

## 4. Gorogoa 

Even though it came out at the end of the year, *Gorogoa* is one of the games I 
will be telling people to play for the next year. It features beautiful 
hand-drawn artwork inside of a puzzle game. While it is pretty short (I finished 
it in a few hours), the artwork and animation alone were worth my time and money. 
If you like beautiful artwork and puzzles, I highly recommend giving it some 
time.

## 5. Galaxy of Pen and Paper

*Galaxy of Pen and Paper* is a follow up to *Knights of Pen and Paper*, taking 
the original premise of a group of people playing a Dungeons and Dragons style 
campaign and shifting it to a science fiction setting. I've only played through 
a portion of the game, but it is a game that seems easy to pick up and do short 
play sessions.

## 6. Universal Paperclips

*Universal Paperclips* is an amusing take on the clicker game. You are the 
computer running a factory that produces paperclips. The more paperclips you 
make, the more your capabilities increase. What could possibly go wrong? Check 
it out if you like clicker games and want something that will devour many hours 
of your life.
