---
title: Kaggle's SQL Scavenger Hunt
author: Brian Richards
date: '2018-03-08'
slug: kaggle-s-sql-scavenger-hunt
categories:
  - SQL
tags:
  - SQL
draft: yes
share: false
comments: false
---

Last month, I participated in [Kaggle's SQL Scavenger Hunt](https://www.kaggle.com/rtatman/sql-scavenger-hunt-handbook/) put together 
by Kaggle Data Preparation Analyst Rachel Tatman. The SQL Scavenger Hunt served 
as an introduction to SQL, BigQuery, and the Python package that Kaggle put 
together to link into their new BigQuery addition. There were 5 different tasks 
sent out over 5 days to answer some questions making use of SQL and BigQuery.

Overall, I thought that the assignments were well written and helped guide me 
through the questions. As someone who is relatively new to SQL (and in the 
process of learning Python), it was great to have some examples to work off of. 
However, I still had some room to experiment and see how the packages worked. 
Thanks Rachel for putting these together!

Check out my work:

* [Day 1](https://www.kaggle.com/bgrich/sql-scavenger-hunt-day-1)
* [Day 2](https://www.kaggle.com/bgrich/sql-scavenger-hunt-day-2)
* [Day 3](https://www.kaggle.com/bgrich/sql-scavenger-hunt-day-3)
* [Day 4](https://www.kaggle.com/bgrich/sql-scavenger-hunt-day-4)
* [Day 5](https://www.kaggle.com/bgrich/sql-scavenger-hunt-day-5)